# Generated by Django 6.0 on 2025-12-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_autor_alter_evento_autor_post_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='autor_post',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=200, verbose_name='apellido de la apersona'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='reseña personal'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre del usuario'),
        ),
    ]
