# Generated by Django 6.0 on 2025-12-11 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_evento_autor_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crear_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos', verbose_name='Imagen')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_evento', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_evento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos', verbose_name='Imagen'),
        ),
    ]
