# Generated by Django 6.0 on 2025-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_evento_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, verbose_name='apellido de la persona'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Evento', verbose_name='Imagen'),
        ),
    ]
